### ISSUE TITLE
[Feature request] Scrolling previews

### ISSUE THREAD

**Issue by wallace11** [kazhala/dotbare#16]
Hi there,
[forgit](https://github.com/wfxr/forgit) has this binding for scrolling previews. I wondered if it was possible for dotbare to have it as well ;)

**Comment by kazhala** [comment]
`fzf` comes a default binding for scrolling previews, `shift-up` and `shift-down` would scroll the preview. You could change the behaviour to `forgit` by creating custom bindings for `dotbare`.

```sh
export DOTBARE_KEY="
  --bind=alt-a:toggle-all       # toggle all selection
  --bind=alt-w:jump             # label jump mode, sort of like vim-easymotion
  --bind=alt-0:top              # set cursor back to top
  --bind=alt-s:toggle-sort      # toggle sorting
  --bind=alt-t:toggle-preview   # toggle preview
  --bind=alt-j:preview-down
  --bind-alt-k:preview-up
"
```

**Comment by kazhala** [comment]
If I miss-understood your question, feel free to re-open.
