### ISSUE TITLE
`dotbare` without arguments fails

### ISSUE THREAD

**Issue by BachoSeven** [kazhala/dotbare#23]
Hi, I noticed that launching `dotbare` without arguments is now broken; I believe it was not before last release. Specifically, it returns:
```
basename: extra operand ‘/opt/dotbare/scripts/fcheckout’
Try 'basename --help' for more information.
```
I experience this with both the AUR release, as well as upstream.

**Comment by kazhala** [comment]
Thanks for reporting, I didn't realize my previous commits broke this feature. It works fine on my macOS machine but I did reproduce it in the docker image.

I just pushed a commit to master which fixed the issue at least during testing in the docker image, could you verify the fix?

**Comment by kazhala** [comment]
Ahh, forgot to add `-0` to `xarg`s when fixing shellcheck stuff. Is it behaving normally now?

**Comment by BachoSeven** [comment]
All good, thanks for the quick fix!
