### ISSUE TITLE
File name is messed on fadd

### ISSUE THREAD

**Issue by denisjv** [kazhala/dotbare#32]
Ive installed dotbare both from source and the aur but this error of the file names being messed up and the preview window still show up not sure if its dotbare or my system 
![2022-07-13_01-45_1](https://user-images.githubusercontent.com/88969730/178668610-15c31efb-66b3-4f34-9953-56069d8c1c0f.png)
![2022-07-13_01-45](https://user-images.githubusercontent.com/88969730/178668613-3a8c6d40-f60f-4542-ada3-10fddec9676e.png)

**Comment by kazhala** [comment]
Hi @denisjv ,

Could you post some of your environment details? OS, shell and the `awk` you are using.

Thanks

**Comment by denisjv** [comment]
OS : Arch Linux
Shell : Fish
Im using the standard awk

**Comment by kazhala** [comment]
Thanks, will take a look to see if I can replicate this when I got some free time. But there are others who's using Arch and having no issues, I doubt fish shell would be the issue, but also could worth a try to see if you could make it work in bash/zsh.

**Comment by denisjv** [comment]
Yea thats what I was thinking ill see what I can do and figure out with the source code thank you

**Comment by denisjv** [comment]
Whats been messing it up for me is `print "\033[32m" substr($0, 1, 1) "\033[31m" substr($0, 2) "\033[0m" ` in the file git_query not so sure why I tested dotbare on another arch linux machine running fish without the wm and all was fine there must be my machine removing the content inside the quotes removed the problem

**Comment by kazhala** [comment]
I'll leave this issue open for now, perhaps someone who also encountered the issue could help out

**Comment by denisjv** [comment]
Thank you cause the problem is back and haven't found a solution

**Comment by denisjv** [comment]
For my solution I stopped just using dotbare fadd and just used dotbare fadd -f instead and that works guess it was just me messing up. Thanks for making dotbare I love it so much.
