### ISSUE TITLE
Can dotbare auto-detect new files in a tracked directory?

### ISSUE THREAD

**Issue by huipengcheng** [kazhala/dotbare#33]
When I add new files to some tracked directories, can dotbare auto stages these new files?

**Comment by kazhala** [comment]
That would depends on git. I don't think git has that capability tho.

**Comment by huipengcheng** [comment]
Me neither.

For me, I casually add some new files to the tracked directory and forget to add these files to stage area (maybe forever). This may be the biggest drawback of the git bare repository I think :)
