### ISSUE TITLE
Feature Request: Clone submodules and a question about .gitignore

### ISSUE THREAD

**Issue by BachoSeven** [kazhala/dotbare#8]
Hi, I just tried migrating my setup to a new arch machine, and dotbare did everything right, except I had a few submodules defined in .gitmodules, none of which where cloned. I don't know if this is intended, but I would like to be able to keep them when migrating.

Also, how is the generated .gitignore file supposed to work? I would guess it's to avoid tracking the bare repo folder, but a) it should not be tracked anyways unless one explicitly adds it; and b) if my bare repo(dotbare_dir) is in .config/dots, with tree in $HOME, and the .gitignore file generated the entry "dots", would it even work? it does not seem to be the correct relative path..

**Comment by kazhala** [comment]
I never thought about submodules yet, but that's certainly a valid feature request, I'll be looking into that, but no guarantee when that's coming yet, I'll spend some time during next week to take a look.

As for the .gitignore, I wasn't even sure if that's needed, and yes, I think you are right, the path is not correct. I'll do some more testing and see if it's actually needed or I'll change how the path is handled.

Thank you so much for this, and please, if you have more feature request, feel free to open up issues.

**Comment by kazhala** [comment]
I've added a option `-s` for `dotbare finit` to allow cloning submodules during checkout. Since cloning bare repository doesn't allow cloning the submodules with them (https://www.git-scm.com/docs/git-clone#Documentation/git-clone.txt---recurse-submodulesltpathspec), it basically will perform a `git module update --init` after the checkout process.

**Comment by BachoSeven** [comment]
That's a really elegant solution, thanks!
