### ISSUE TITLE
Ssh cloning support

### ISSUE THREAD

**Issue by BachoSeven** [kazhala/dotbare#9]
I am not sure how you would implement this, but I would like to be set authentication through ssh for pushing. One way to do it manually after pulling is to change https=>ssh as explained [here](https://pandammonium.org/how-to-change-a-git-repository-from-https-to-ssh/).

One issue is that someone could have their ssh config IN the dotfiles, maybe.

**Comment by kazhala** [comment]
I'm not so sure if I understand your request correctly, is it just to change the remote origin to an ssh origin? Correct me if I understand it wrong.

With the above understanding, I think this is more appropriate to let the user handle it. When it comes to the settings of the bare repo, it should be defined and manipulated by the user.

That being said, you could easily add the steps explained in the post to your bootstrap script and run the script after `dotbare` migration.

**Comment by BachoSeven** [comment]
My reasoning was that when migrating to a new machine, if following [these](https://github.com/kazhala/dotbare/#migrating-dotbare-to-a-new-system) steps, one would let `dotbare` handle setting up the bare repo, after you configure its location.

So for my purpose one could not run finit -u <link> and just clone the bare repo? What w

**Comment by kazhala** [comment]
So I've just tested the ssh cloning, the URL of `dotbare finit -u URL` can just be the ssh URL from Github and it will work the same. After the clone with the ssh URL, when you push, it will just use the ssh credentials. I'm still not sure if that's what you wanted. If this is what you mean, I should probably adjust the wording in README. Below is a demo.
![Screen Recording 2020-06-08 at 11 54 45](https://user-images.githubusercontent.com/43941510/83986338-d3f1c780-a97f-11ea-92a3-1df8e46a1fb4.gif)

**Comment by BachoSeven** [comment]
Yes, that makes a lot of sense and is exactly what I meant. Thanks for clarifying
